---

- name: Update YUM and install common packages
  yum: name={{item}} state=present
  with_items:
    - vim
    - git-core
    - mercurial
    - python-pycurl
    - libxml2
    - libxml2-devel
    - libjpeg-turbo
    - libjpeg-turbo-devel
    - libxslt
    - libxslt-devel
    - gcc

- name: Disable iptables
  service: name=iptables state=stopped
